name: "Rust Ticket Assistant"
description: "Detects potential duplicate issues, relationships between tickets, and related PRs, then comments on the issue."
author: "Marco Kuidja "
inputs:
  enable_fib:
    description: "Action does nothing"
    required: true
  max_threshhold: 
    description: "The maximum number action should compute"
    required: true
  pr_number:
    description: "The pull request number."
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.enable_fib }}
    - ${{ inputs.max_threshhold }}
    - ${{ inputs.pr_number }}