name: Compute Fibbonacci on PR content

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fibbot:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Rust Action
        uses: ./
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          enable_fib: true 
          max_threshhold: 105
